services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:5173,http://10.1.27.19:5173
      - YOTO_CLIENT_ID=${YOTO_CLIENT_ID}
      - YOTO_SCOPE=${YOTO_SCOPE}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_TARGET=http://backend:8001
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend
